name: Send Email on Push

on: [push]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Email Script
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: python send_email.py
